version: '3.8'

services:
  db:
   image: mysql:5.6
   volumes:
     - mysql:/var/lib/mysql
   env_file:
     - '.env.db'

  flightLoads:
    image: flight-load-py
    stdin_open: true
    tty: true
    build:
      context: .
    volumes:
      - .:/app
    env_file:
     - '.env'

volumes:
  mysql:
